#!/bin/zsh


# Machine-specific env (create locally; not in dotfiles)
[ -r "$HOME/.zshenv.local" ] && . "$HOME/.zshenv.local"
[ -r "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# Comments next to commands
setopt INTERACTIVECOMMENTS

# Enable bash-like expansion for things like arrayutil.
setopt SH_WORD_SPLIT
