vim.opt.nu=true
vim.opt.rnu=true
vim.opt.mouse="a"                   -- Enable mouse for scrolling and resizing.
vim.opt.tabstop=4                   -- Indent using four spaces.
vim.opt.shiftwidth=4                -- When shifting, indent using four spaces.
vim.opt.expandtab=true              -- Convert tabs to spaces.
vim.opt.smartindent=true
vim.opt.termguicolors=true
vim.opt.clipboard="unnamedplus"
-- vim.opt.clipboard="unnamed"
vim.opt.splitbelow=true
vim.opt.splitright=true
vim.opt.spell=true
vim.opt.spelllang=en_us
vim.opt.ignorecase=true
vim.opt.smartcase=true
vim.opt.incsearch=true
vim.g.mapleader=" "                 -- Map the leader
vim.g.oscyank_term='default'        -- needed for playing nicely with tmux
vim.opt.syntax = "on"
vim.opt.tabstop=2
vim.opt.shiftwidth=2
vim.opt.expandtab=true
vim.opt.ruler=true
vim.opt.smartindent=true
vim.opt.nu=true                     -- Display line numbers in gutter.
vim.opt.number=true
vim.opt.numberwidth=2
vim.opt.cpoptions= vim.opt.cpoptions + "n"
vim.opt.hlsearch=true
vim.opt.lazyredraw=true
vim.cmd("set wrap linebreak nolist")
vim.opt.wrap=true
vim.opt.linebreak=true
vim.opt.cursorline=true
vim.opt.relativenumber=false