vim.opt.wildignore = vim.opt.wildignore + '*/buck-out/*'
vim.opt.wildignore = vim.opt.wildignore + '*/target/*'
vim.opt.wildignore = vim.opt.wildignore + '*/tmp/*'                         -- Ignore temporary directories
vim.opt.wildignore = vim.opt.wildignore + '*.so'
vim.opt.wildignore = vim.opt.wildignore + '*.swp'                           -- Ignore common VIM files
vim.opt.wildignore = vim.opt.wildignore + '*.zip,*.rar,*.7z,*.gz'           -- Ignore compressed archives
vim.opt.wildignore = vim.opt.wildignore + '.DS_Store'                       -- Ignore MacOS DS_Store files
vim.opt.wildignore = vim.opt.wildignore + '*.pyc'
vim.opt.wildignore = vim.opt.wildignore + '**/.git/*,**/.hg/*,**/.svn/*'    -- Ignore version control directories
vim.opt.wildignore = vim.opt.wildignore + '*/.pants.d/**'
vim.opt.wildignore = vim.opt.wildignore + '*/dist/**'
vim.opt.wildignore = vim.opt.wildignore + '*.csv'
vim.opt.wildignore = vim.opt.wildignore + '*.class'
vim.opt.wildignore = vim.opt.wildignore + '*.pyc,__pycache__'               -- Ignore common python objects
vim.opt.wildignore = vim.opt.wildignore + '**/node_modules/*'
vim.opt.wildignore = vim.opt.wildignore + '**/android/*'
vim.opt.wildignore = vim.opt.wildignore + '**/ios/*'
vim.opt.wildignore = vim.opt.wildignore + '*_build/*'