#!/bin/bash

# Go toolchain and workspace (generic: standard $HOME/go)
if [ -d "${HOMEBREW_PREFIX:-/usr/local}/opt/go/libexec/bin" ]; then
	# shellcheck disable=2086
	PATH=$(IFS=:; prepend "${HOMEBREW_PREFIX:-/usr/local}/opt/go/libexec/bin" $PATH)
fi

export GOPATH="${GOPATH:-$HOME/go}"
# shellcheck disable=2086
PATH=$(IFS=:; prepend "$GOPATH/bin" $PATH)

export PATH
